---
version: '3'

x-icinga2-certs: &x-icinga2-certs
  depends_on:
    icinga2-ca:
      condition: service_completed_successfully
  image: icinga/icinga2
  command:
    - icinga2
    - api
    - setup

x-ido-schema: &x-ido-schema
  image: mariadb:10
  volumes:
    - ./volumes/icinga2/schema:/schema:ro

x-ido: &x-ido
  image: mariadb:10
  environment:
    MARIADB_RANDOM_ROOT_PASSWORD: '1'
    MARIADB_USER: ido
    MARIADB_PASSWORD: ido
    MARIADB_DATABASE: ido

x-dbicinga: &x-dbicinga
  image: mariadb:10
  environment:
    MARIADB_RANDOM_ROOT_PASSWORD: '1'
    MARIADB_USER: icingadb
    MARIADB_PASSWORD: icingadb
    MARIADB_DATABASE: icingadb

x-icingadb-env: &x-icingadb-env
  ICINGADB_REDIS_PORT: '6379'
  ICINGADB_DATABASE_DATABASE: icingadb
  ICINGADB_DATABASE_USER: icingadb
  ICINGADB_DATABASE_PASSWORD: icingadb

x-dbweb: &x-dbweb
  image: mariadb:10
  environment:
    MARIADB_RANDOM_ROOT_PASSWORD: '1'
    MARIADB_USER: icingaweb2
    MARIADB_PASSWORD: icingaweb2
    MARIADB_DATABASE: icingaweb2

x-web-env: &x-web-env
  icingaweb.enabledModules: icingadb,monitoring
  icingaweb.passwords.icingaweb2.icingaadmin: icinga

  icingaweb.authentication.icingaweb2.backend: db
  icingaweb.authentication.icingaweb2.resource: icingaweb_db

  icingaweb.config.global.config_resource: icingaweb_db
  icingaweb.config.global.show_application_state_messages: '1'
  icingaweb.config.global.show_stacktraces: '1'
  icingaweb.config.logging.log: php
  icingaweb.config.logging.level: WARNING
  icingaweb.config.logging.application: icingaweb2

  icingaweb.groups.icingaweb2.backend: db
  icingaweb.groups.icingaweb2.resource: icingaweb_db

  icingaweb.modules.icingadb.commandtransports.icinga2.transport: api
  icingaweb.modules.icingadb.commandtransports.icinga2.port: '5665'
  icingaweb.modules.icingadb.commandtransports.icinga2.username: root
  icingaweb.modules.icingadb.commandtransports.icinga2.password: icinga
  icingaweb.modules.icingadb.config.icingadb.resource: icingadb
  icingaweb.modules.icingadb.redis.redis1.port: '6379'

  icingaweb.modules.monitoring.backends.icinga.type: ido
  icingaweb.modules.monitoring.backends.icinga.resource: icinga_ido

  icingaweb.modules.monitoring.commandtransports.icinga2.transport: api
  icingaweb.modules.monitoring.commandtransports.icinga2.port: '5665'
  icingaweb.modules.monitoring.commandtransports.icinga2.username: root
  icingaweb.modules.monitoring.commandtransports.icinga2.password: icinga

  icingaweb.modules.monitoring.config.security.protected_customvars: '*pw*,*pass*,community'

  icingaweb.resources.icingaweb_db.type: db
  icingaweb.resources.icingaweb_db.db: mysql
  icingaweb.resources.icingaweb_db.dbname: icingaweb2
  icingaweb.resources.icingaweb_db.username: icingaweb2
  icingaweb.resources.icingaweb_db.password: icingaweb2
  icingaweb.resources.icingaweb_db.charset: utf8

  icingaweb.resources.icingadb.type: db
  icingaweb.resources.icingadb.db: mysql
  icingaweb.resources.icingadb.dbname: icingadb
  icingaweb.resources.icingadb.username: icingadb
  icingaweb.resources.icingadb.password: icingadb
  icingaweb.resources.icingadb.charset: utf8mb4

  icingaweb.resources.icinga_ido.type: db
  icingaweb.resources.icinga_ido.db: mysql
  icingaweb.resources.icinga_ido.dbname: ido
  icingaweb.resources.icinga_ido.username: ido
  icingaweb.resources.icinga_ido.password: ido

  icingaweb.roles.Administrators.users: icingaadmin
  icingaweb.roles.Administrators.permissions: '*'
  icingaweb.roles.Administrators.groups: Administrators

services:
  icinga2-ca:
    image: icinga/icinga2
    command:
      - bash
      - -exo
      - pipefail
      - -c
      - test -e /var/lib/icinga2/ca/ca.crt || icinga2 pki new-ca
    volumes:
      - ./volumes/icinga2/ca:/data

  ido-schema:
    image: icinga/icinga2
    entrypoint: ''
    command:
      - cp
      - /usr/share/icinga2-ido-mysql/schema/mysql.sql
      - /schema
    volumes:
      - ./volumes/icinga2/schema:/schema

  master1-certs:
    <<: *x-icinga2-certs
    hostname: master1
    volumes:
      - ./volumes/icinga2/master1:/data
      - ./volumes/icinga2/ca/var/lib/icinga2/ca:/data/var/lib/icinga2/ca:ro

  master1:
    depends_on:
      master1-certs:
        condition: service_completed_successfully
      ido1:
        condition: service_started
      redis1:
        condition: service_started
    hostname: master1
    image: icinga/icinga2
    volumes:
      - ./volumes/icinga2/master1:/data
      - ./icinga2.conf:/data/etc/icinga2/icinga2.conf:ro
      - ./volumes/icinga2/ca/var/lib/icinga2/ca:/data/var/lib/icinga2/ca:ro

  ido-schema1:
    <<: *x-ido-schema
    depends_on:
      ido-schema:
        condition: service_completed_successfully
      ido1:
        condition: service_started
    command:
      - bash
      - -exo
      - pipefail
      - -c
      - |
          while ! mysql -hido1 -uido -pido ido </schema/mysql.sql
          do sleep 3
          done

  ido1:
    <<: *x-ido
    volumes:
      - ./volumes/ido/1:/var/lib/mysql

  redis1:
    image: redis:alpine
    volumes:
      - ./volumes/redis/1:/data

  dbicinga1:
    <<: *x-dbicinga
    volumes:
      - ./volumes/dbicinga/1:/var/lib/mysql

  icingadb1:
    depends_on:
      redis1:
        condition: service_started
      dbicinga1:
        condition: service_started
    image: icinga/icingadb
    environment:
      <<: *x-icingadb-env
      ICINGADB_REDIS_HOST: redis1
      ICINGADB_DATABASE_HOST: dbicinga1

  web1:
    depends_on:
      dbweb1:
        condition: service_started
      dbicinga1:
        condition: service_started
      redis1:
        condition: service_started
    image: icinga/icingaweb2
    ports:
      - 8081:8080
    environment:
      <<: *x-web-env
      icingaweb.modules.icingadb.commandtransports.icinga2.host: master1
      icingaweb.modules.icingadb.redis.redis1.host: redis1
      icingaweb.modules.monitoring.commandtransports.icinga2.host: master1
      icingaweb.resources.icingaweb_db.host: dbweb1
      icingaweb.resources.icingadb.host: dbicinga1
      icingaweb.resources.icinga_ido.host: ido1
    volumes:
      - ./volumes/icingaweb2/1:/data

  dbweb1:
    <<: *x-dbweb
    volumes:
      - ./volumes/dbweb/1:/var/lib/mysql

  master2-certs:
    <<: *x-icinga2-certs
    hostname: master2
    volumes:
      - ./volumes/icinga2/master2:/data
      - ./volumes/icinga2/ca/var/lib/icinga2/ca:/data/var/lib/icinga2/ca:ro

  master2:
    depends_on:
      master2-certs:
        condition: service_completed_successfully
      ido2:
        condition: service_started
      redis2:
        condition: service_started
    hostname: master2
    image: icinga/icinga2
    volumes:
      - ./volumes/icinga2/master2:/data
      - ./icinga2.conf:/data/etc/icinga2/icinga2.conf:ro
      - ./volumes/icinga2/ca/var/lib/icinga2/ca:/data/var/lib/icinga2/ca:ro

  ido-schema2:
    <<: *x-ido-schema
    depends_on:
      ido-schema:
        condition: service_completed_successfully
      ido2:
        condition: service_started
    command:
      - bash
      - -exo
      - pipefail
      - -c
      - |
          while ! mysql -hido2 -uido -pido ido </schema/mysql.sql
          do sleep 3
          done

  ido2:
    <<: *x-ido
    volumes:
      - ./volumes/ido/2:/var/lib/mysql

  redis2:
    image: redis:alpine
    volumes:
      - ./volumes/redis/2:/data

  dbicinga2:
    <<: *x-dbicinga
    volumes:
      - ./volumes/dbicinga/2:/var/lib/mysql

  icingadb2:
    depends_on:
      redis2:
        condition: service_started
      dbicinga2:
        condition: service_started
    image: icinga/icingadb
    environment:
      <<: *x-icingadb-env
      ICINGADB_REDIS_HOST: redis2
      ICINGADB_DATABASE_HOST: dbicinga2

  web2:
    depends_on:
      dbweb2:
        condition: service_started
      dbicinga2:
        condition: service_started
      redis2:
        condition: service_started
    image: icinga/icingaweb2
    ports:
      - 8082:8080
    environment:
      <<: *x-web-env
      icingaweb.modules.icingadb.commandtransports.icinga2.host: master2
      icingaweb.modules.icingadb.redis.redis1.host: redis2
      icingaweb.modules.monitoring.commandtransports.icinga2.host: master2
      icingaweb.resources.icingaweb_db.host: dbweb2
      icingaweb.resources.icingadb.host: dbicinga2
      icingaweb.resources.icinga_ido.host: ido2
    volumes:
      - ./volumes/icingaweb2/2:/data

  dbweb2:
    <<: *x-dbweb
    volumes:
      - ./volumes/dbweb/2:/var/lib/mysql
